/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./components/Layout/TopHeader/AddButton.vue')['default']
    App: typeof import('./App.vue')['default']
    AuthBtn: typeof import('./components/auth/AuthBtn.vue')['default']
    AuthForm: typeof import('./components/auth/AuthForm.vue')['default']
    AuthInput: typeof import('./components/auth/AuthInput.vue')['default']
    AuthLogo: typeof import('./components/auth/AuthLogo.vue')['default']
    AuthPasswordInput: typeof import('./components/auth/AuthPasswordInput.vue')['default']
    AuthVerificationCodeInput: typeof import('./components/auth/AuthVerificationCodeInput.vue')['default']
    AuthWrapForm: typeof import('./components/auth/AuthWrapForm.vue')['default']
    BackButton: typeof import('./components/Layout/TopHeader/BackButton.vue')['default']
    ErrorAlert: typeof import('./components/Layout/ErrorAlert.vue')['default']
    ForgotPassword: typeof import('./views/auth/ForgotPassword.vue')['default']
    ListSkeleton: typeof import('./components/Layout/Skeleton/ListSkeleton.vue')['default']
    Login: typeof import('./views/auth/Login.vue')['default']
    Logout: typeof import('./components/auth/Logout.vue')['default']
    LogsActions: typeof import('./components/Layout/TopHeader/LogsActions.vue')['default']
    NavbarSide: typeof import('./components/Layout/Sidebar/NavbarSide.vue')['default']
    Notifications: typeof import('./components/Layout/TopHeader/Notifications.vue')['default']
    ProfileMenu: typeof import('./components/Layout/TopHeader/ProfileMenu.vue')['default']
    ResetPassword: typeof import('./views/auth/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Layout/Sidebar/Sidebar.vue')['default']
    SidebarDrawer: typeof import('./components/Layout/Sidebar/SidebarDrawer.vue')['default']
    SuccessAlert: typeof import('./components/Layout/SuccessAlert.vue')['default']
    Table: typeof import('./components/Layout/Tables/Table.vue')['default']
    TermsAndCondition: typeof import('./views/TermsAndCondition.vue')['default']
    ToggleMobile: typeof import('./components/Layout/TopHeader/ToggleMobile.vue')['default']
    TopBadgerBanner: typeof import('./components/Layout/TopHeader/TopBadgerBanner.vue')['default']
    TopHeader: typeof import('./components/Layout/TopHeader/TopHeader.vue')['default']
    TopSearchBar: typeof import('./components/Layout/TopHeader/TopSearchBar.vue')['default']
    WarningAlert: typeof import('./components/Layout/WarningAlert.vue')['default']
    Welcome: typeof import('./views/Welcome.vue')['default']
  }
}
